name: Publish to Docker - Development

on:
  push:
    branches: [ yocsef ]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

env:
  APP_NAME: moss_frontend

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag version
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:yocsef

      - name: Login to Aliyun ACR
        uses: aliyun/acr-login@master
        with:
          login-server: https://registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Aliyun ACR
        uses: docker/build-push-action@master
        with:
          push: true
          tags: |
            registry.cn-shanghai.aliyuncs.com/${{ secrets.ACR_NAMESPACE }}/${{ env.APP_NAME }}:yocsef
